services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - viewpoint-net

networks:
  viewpoint-net:
    name: viewpoint-net
    driver: bridge